name: build container -> kde-bootc
run-name: building container -> kde-bootc
on: 
  workflow_dispatch:
  # push:                     # Disable rebuild at push
  schedule:
  - cron: '0 0 */3 * *'       # Run at 12:00 AM every 3 days


jobs:
  io-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run podman build
      run: podman build -t kde-bootc --disable-compression=false .
    - name: push image to ghcr.io
      run: podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} kde-bootc ghcr.io/lordpong/kde-bootc:latest
